version: '3.0'

services:
  node:
    container_name: Node
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.node
      args:
        - NODE_ENV
    volumes:
      - ../src:/app/src
      - ../dist:/app/dist
      - ../node_modules:/app/node_modules
    environment:
      - NODE_ENV
    ports:
      - 8080:8080
      - 5001:5000
      - 9229:9229
    networks:
      - nest-network
    depends_on:
      - db

  db:
    container_name: Postgres
    image: postgres
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./conf/my-postgres.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      - nest-network

  adminer:
    container_name: Adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - nest-network
    depends_on:
      - db

networks:
  nest-network:
    driver: bridge
