FROM node:18.12

ARG NODE_ENV=${NODE_ENV}
ENV DEBUG=${DEBUG}
WORKDIR /app

COPY package.json ./
COPY yarn.lock ./
COPY tsconfig.json ./
COPY .${NODE_ENV}.env ./

# If you are building your code for production
# RUN npm ci --only=production

CMD [ "yarn", "start:nest-debug" ]

